// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9HJWo40jUayXhFen9_DHx0Wbo7o-fmA',
    appId: '1:850909463684:web:b7dacb0417744be33deed1',
    messagingSenderId: '850909463684',
    projectId: 'home-hire-f6d96',
    authDomain: 'home-hire-f6d96.firebaseapp.com',
    storageBucket: 'home-hire-f6d96.appspot.com',
    measurementId: 'G-7QFRY3RV11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5dbAL5hfe5t77xdMP8E6gY5rUF3M3w0',
    appId: '1:850909463684:android:65002e6f02bc856f3deed1',
    messagingSenderId: '850909463684',
    projectId: 'home-hire-f6d96',
    storageBucket: 'home-hire-f6d96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTOnCLKa4yRd1nH_VzhJYIqNgR2p1fKg',
    appId: '1:850909463684:ios:6c4f79e522f5eb4e3deed1',
    messagingSenderId: '850909463684',
    projectId: 'home-hire-f6d96',
    storageBucket: 'home-hire-f6d96.appspot.com',
    iosClientId:
        '850909463684-76h78ll31gsnsmvt6j67tj465u4bfrio.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeHireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTOnCLKa4yRd1nH_VzhJYIqNgR2p1fKg',
    appId: '1:850909463684:ios:6c4f79e522f5eb4e3deed1',
    messagingSenderId: '850909463684',
    projectId: 'home-hire-f6d96',
    storageBucket: 'home-hire-f6d96.appspot.com',
    iosClientId:
        '850909463684-76h78ll31gsnsmvt6j67tj465u4bfrio.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeHireApp',
  );
}
